spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          query:
            timeout: 50
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost}:${PORT_DB:5432}/db_propostas
    username: keycloak
    password: password

#CONFIGURAÇÕES DE SEGURANÇA DO ACTUATOR
management:
  endpoint:
    web:
      exposure:
        include: health
        exclude: env,beans
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET
#HABILITA OU NAO OS DETALHES DA CHECAGEM
#    health:
#      show-details: always

#CONFIGURAÇÕES DE TIMEOUT DO FEIGN
feign:
  client:
    config:
      analises:
        readTimeout: 5000
        connectTimeout: 50000

#CONFIGURAÇÃO SERVIÇOS EXTERNOS
analises:
  url: http://${HOST_SISTEMA_ANALISE:localhost}:${PORT_SISTEMA_ANALISE:9999}/api/solicitacao
cartoes:
  url: http://${HOST_SISTEMA_CARTOES:localhost}:${PORT_SISTEMA_CARTOES:8888}/api/cartoes

#CONFIGURAÇÃO DE TASKS
periodicidade:
  atrela-cartao: ${PERIODICIDADE_ATRELA_CARTAO:20000}