spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          query:
            timeout: 50
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${HOST_DB:localhost:5432/db_propostas}
    username: keycloak
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/proposta}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/proposta/protocol/openid-connect/certs}

#CONFIGURAÇÕES DE SEGURANÇA DO ACTUATOR
management:
  endpoint:
    web:
      exposure:
        include: health
        exclude: env,beans
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET
#HABILITA OU NAO OS DETALHES DA CHECAGEM
#    health:
#      show-details: always

#CONFIGURAÇÕES DE TIMEOUT DO FEIGN
feign:
  client:
    config:
      analises:
        readTimeout: 5000
        connectTimeout: 50000

#CONFIGURAÇÃO SERVIÇOS EXTERNOS
analises:
  url: ${URL_SISTEMA_ANALISE:http://localhost:9999/api/solicitacao}
cartoes:
  url: ${URL_SISTEMA_CARTOES:http://localhost:8888/api/cartoes}

#CONFIGURAÇÃO DE TASKS
periodicidade:
  atrela-cartao: ${PERIODICIDADE_ATRELA_CARTAO:20000}
