spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      javax:
        persistence:
          query:
            timeout: 50
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/db_propostas
    username: keycloak
    password: password

#CONFIGURAÇÕES DE SEGURANÇA DO ACTUATOR
management:
  endpoint:
    web:
      exposure:
        include: health
        exclude: env,beans
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET
#HABILITA OU NAO OS DETALHES DA CHECAGEM
#    health:
#      show-details: always

#CONFIGURAÇÕES DE TIMEOUT DO FEIGN
feign:
  client:
    config:
      analises:
        read-timeout: 100
        connect-timeout: 100

#CONFIGURAÇÃO SERVIÇOS EXTERNOS
analises:
  url: ${URL_SISTEMA_ANALISE:http://localhost:9999/api/solicitacao}